### ISSUE TITLE
Syntax errors when browsing with some versions of IE11

### ISSUE THREAD

**Issue by alexbenitez** [Luteceo/aspnet-starter-kit-2.0#34] opened 2018-09-15 04:16 UTC
For some reason I'm getting (two) syntax errors when browsing with some versions of IE11. Browsing with version 11.285.17134.0 crashes whereas with 11.2430.14393.0 is OK. (Chrome is OK all the time). At work I have the same problem (they don't have the most recent IE).

Is there any npm module that needs update,  workaround or something to make the starter work with IE?

![ie_crash](https://user-images.githubusercontent.com/8364054/45582321-777d7900-b87b-11e8-98e6-1cf6dbce6df2.PNG)
```
	// getDefaultExport function for compatibility with non-harmony modules
 	__webpack_require__.n = function(module) {
 		var getter = module && module.__esModule ?
 			function getDefault() { return module['default']; } :
 			function getModuleExports() { return module; };
 		__webpack_require__.d(getter, 'a', getter);
 		return getter;
 	};
```

**Comment by tjaskula** [comment] 2018-09-15 08:46
I don't have IE on my machine to reproduce the issue. Could you post the stack trace and the error that is reported in the console ? I'll try to figure out what that might be.

**Comment by alexbenitez** [comment] 2018-09-15 15:31
The problem is gone by using the compatibility  metadata to emulate Edge as the first meta tag.
```
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
```

I can't manage to have IE properly break to see something in the stack (e.g. have no problem debugging js with other apps). It appears it breaks immediately... probably within a the webpack=bootstrap plug in or when it is loaded?

If I click on the error hyperlinks they take me to (but no stack trace info):

webpack:///webpack/bootstrap
```
return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}
```

and 

vendor.js
```
// getDefaultExport function for compatibility with non-harmony modules
 	__webpack_require__.n = function(module) {
 		var getter = module && module.__esModule ?
 			function getDefault() { return module['default']; } :
 			function getModuleExports() { return module; };
 		__webpack_require__.d(getter, 'a', getter);
 		return getter;
 	};
```

Perhaps the problem is gone by upgrading to Bootstrap 4? Unfortunately I don't have the time to investigate further (for the moment). 

Using Edge it detects more syntax errors but does properly display the web pages (so I'm not 100% sure the errors I get with Edge are exactly the same I see with older versions of IE11). 

![capture2](https://user-images.githubusercontent.com/8364054/45587744-133cd280-b8d8-11e8-9193-7d22c517431d.PNG)

You can emulate IE using Safari if you have a MacOS and see what appears to be the same error (you can follow this steps : https://www.imore.com/how-view-websites-your-mac-require-internet-explorer-or-pc). Edge and Safari emulating EI fails when loading bootstrap.

![screen shot 2018-09-15 at 11 16 16 am](https://user-images.githubusercontent.com/8364054/45587810-11274380-b8d9-11e8-869b-90be0b7b5bb4.png)

Most solutions involving MS .net core are expected to work with Edge and at least any IE11. I would use the compatibility tag to the starter...

By all means, if you can deploy this or any fix somewhere I'll be happy to browse using my old IE11 (the minor version that crashes) and let you know.

/Alex

**Comment by tjaskula** [comment] 2018-09-19 07:30
I've tried different things but cannot really reproduce the issue setting the user agent to IE11. I have also a Windows machine with IE 11 which is unfortunatelly more recent then the version causing the crashes so the bug doesn't occur either.

Is this occuring also when you're not in debug mode `yarn start` but once the project was published `yarn run publish` I'm trying to  figure out if this may come from specific webpack configuration in debug mode or something else.

**Comment by alexbenitez** [comment] 2018-09-19 11:02
Do you have the starter deployed somewhere so I can give it a try from some machines with IE11?

**Comment by alexbenitez** [comment] 2018-09-19 12:49
Not entirely sure but it might be related with the use of commonjs & es6 vs es2015 & es5.

I took and old ms starter targeting 2.0 and switched it  to 2.1, upgraded React to 16, Typescript 3 etc... the moment I switched the module and target setting in tsconfig.json I started to get similar errors in IE 11 (Chrome is OK).

**Comment by alexbenitez** [comment] 2018-09-19 16:11
It appears the problem is that babel is not transpiling properly for IE11 since it fails when instantiating the react components... Probably the unsupported keywork "class".
-----------
I installed the @babel/preset-env package to transpile to ES5 (which is what IE11 needs) and now I get a different error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.

These are the changes:
```
"devDependencies": {
    "@babel/core": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@types/history": "4.7.0",
```

```
"dependencies": {
    "@babel/polyfill": "^7.0.0",
    "npm": "^6.4.1"
```

```
 rules: [
              { 
                test: /\.tsx?$/, include: /client/,
               // exclude: /(node_modules|bower_components)/,
                use: [
                  {
                    loader: 'babel-loader',
                    options: {
                      babelrc: false,
                      plugins: ['react-hot-loader/babel'],
                      presets: ['@babel/preset-env']
                    },
                  },
                  'awesome-typescript-loader?silent=true', // (or awesome-typescript-loader)
                ]},
              { test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' }
            ]
```

boot-client.tsx and boot-server.tsx (at the very top)

```
import "@babel/polyfill";
```

**Comment by tjaskula** [comment] 2018-09-21 20:53
@alexbenitez I've made some changes here https://github.com/Luteceo/aspnet-starter-kit-2.0/pull/40. I'm not sure it fixes the issue but if you have some time to try it out that would be nice

**Comment by tjaskula** [comment] 2018-12-11 20:33
I'm closing the issue as I cannot reproduce it and there was no more activity on it.

**Closed as completed by tjaskula** 2018-12-11 20:33 UTC
Labels: old browser
